version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8200:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key_change_in_production
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=studioflow
      - SQL_USER=studioflow_user
      - SQL_PASSWORD=studioflow_password
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3200:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8200/api/v1
    depends_on:
      - backend
    command: npm run dev

  # Database service
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=studioflow
      - POSTGRES_USER=studioflow_user
      - POSTGRES_PASSWORD=studioflow_password
    ports:
      - "5433:5432"

volumes:
  postgres_data: