# Generated by Django 5.0.14 on 2025-09-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(choices=[('studioflow_basic', 'StudioFlow Básico'), ('studioflow_pro', 'StudioFlow Pro')], default='studioflow_basic', max_length=20, verbose_name='plano')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Vencida'), ('CANCELED', 'Cancelada'), ('UNPAID', 'Não Paga')], default='TRIAL', max_length=10, verbose_name='status')),
                ('trial_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início do trial')),
                ('trial_end', models.DateTimeField(default=migrations.RunPython(lambda: django.utils.timezone.now() + django.utils.timezone.timedelta(days=15)), verbose_name='fim do trial')),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início do período atual')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='fim do período atual')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='cancelar no fim do período')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='data de cancelamento')),
                ('payment_method_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do método de pagamento')),
                ('mercadopago_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do cliente Mercado Pago')),
                ('mercadopago_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da assinatura Mercado Pago')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='último pagamento')),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='próximo pagamento')),
                ('amount', models.DecimalField(decimal_places=2, default=19.99, max_digits=10, verbose_name='valor')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='moeda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]