# Generated by Django 5.0.14 on 2025-09-24 18:01

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="trial_end",
            field=models.DateTimeField(
                default=subscriptions.models.get_trial_end_default,
                verbose_name="fim do trial",
            ),
        ),
    ]
