# Generated by Django 5.0.14 on 2025-07-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("capacidade", models.PositiveIntegerField(verbose_name="capacidade")),
                (
                    "preco_hora",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço por hora"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "is_disponivel",
                    models.BooleanField(default=True, verbose_name="disponível"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "sala",
                "verbose_name_plural": "salas",
                "ordering": ["nome"],
            },
        ),
    ]
