# Generated by Django 5.0.14 on 2025-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CLIENTE", "Cliente"),
                    ("PRESTADOR", "Prestador"),
                ],
                default="CLIENTE",
                max_length=10,
                verbose_name="tipo de usuário",
            ),
        ),
    ]
